### ISSUE TITLE
请问下plot1.py文件的作用是什么？

### ISSUE THREAD

**Issue by yyl424525** [hjjpku/Attention_in_Graph#3]
在运行此文件后，输出下面的结果，请问下下面的结果是什么意思啊？
`
1       0.5559  0.0805  0.5559  0.5559  0.5559   
max 0.555885  
2       0.5559  0.0805  0.5559  0.5559  0.5559  
max 0.555885
3       0.5559  0.0805  0.5500  0.5559  0.5559
max 0.555885
4       0.5529  0.0819  0.5618  0.5529  0.5559
max 0.555885
5       0.5588  0.0911  0.5706  0.5500  0.5470

...
`

**Comment by hjjpku** [comment]
The file plot1.py serves to calculate the averaged accuracy of 10-fold tests. Each line of the output is the averaged acc of the 10 tests at the corresponding training epochs (i.e. line i for models at epoch i).

**Comment by hjjpku** [comment]
The first column of the output indicate the number of epoch;  the second column shows the result of our hierarchical prediction architechture. the variation of acc ahieved by different

**Comment by hjjpku** [comment]
The first column of the output indicates the number of epoch; the second column shows the result of our hierarchical prediction architechture. Then, there are the variation of acc achieved by different AttGCN layers and the acc of each AttGCN layers. The last column is the best performance achieved by the model so far.

**Comment by yyl424525** [comment]
> The file plot1.py serves to calculate the averaged accuracy of 10-fold tests. Each line of the output is the averaged acc of the 10 tests at the corresponding training epochs (i.e. line i for models at epoch i).

Nice work. Thank you!
