### ISSUE TITLE
表格1里的“AVG”具体是如何计算的

### ISSUE THREAD

**Issue by yyl424525** [hjjpku/Attention_in_Graph#4]
作者的思路很新颖，对此篇文章比较感兴趣，请问下实验里的表格1里的“AVG”具体是如何计算的呀？

**Comment by zoharli** [comment]
“AVG“是把不同层的分类器输出的softmax概率取平均，再取最大值作为分类结果。

**Comment by yyl424525** [comment]
@zoharli，非常感谢
