### ISSUE TITLE
作者的交叉验证思路是哪种？

### ISSUE THREAD

**Issue by yyl424525** [hjjpku/Attention_in_Graph#5]
作者好，我看文中说使用10-fold交叉验证，但是不太懂文中如何做测试的，请问下是下面之一还是其他的思路吗

1. 用这100k条数据做k-fold交叉验证，来调模型参数

2. 先随机划分出70k条数据做训练集用来根据交叉验证调参数，调好之后再用剩下的30k条数据做测试集

3. 其他？

**Comment by zoharli** [comment]
交叉验证的思路是用9：1的划分比例做10fold交叉验证，即每个epoch有10个精度输出，再取10个精度的平均值最大的epoch的checkpoint作为训练完成的模型，这个方法是与文中对比的其他工作保持一致的

**Comment by yyl424525** [comment]
> 交叉验证的思路是用9：1的划分比例做10fold交叉验证，即每个epoch有10个精度输出，再取10个精度的平均值最大的epoch的checkpoint作为训练完成的模型，这个方法是与文中对比的其他工作保持一致的

非常感谢！
